name: Deploy to Production MoCA App

on:
  push:
    branches:
      - main

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install FortiClient VPN
      run: |
        sudo apt-get update
        sudo apt-get install -y forticlient
      if: \${{ failure() }}
      continue-on-error: true
      
    - name: Connect to VPN
      if: \${{ success() }}
      env:
        VPN_USERNAME: \${{ secrets.VPN_USERNAME }}
        VPN_PASSWORD: \${{ secrets.VPN_PASSWORD }}
      run: |
        ./connect_vpn.sh

    - name: Deploy to Production Server
      if: \${{ success() }}
      env:
        SSH_USER: \${{ secrets.PRODUCTION_SSH_USER }}
        SSH_HOST: \${{ secrets.PRODUCTION_SSH_HOST }}
        SSH_PASSWORD: \${{ secrets.PRODUCTION_SSH_PASSWORD }}
      run: |
        # Conectarse al servidor mediante SSH
        sshpass -p "\$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no "\$SSH_USER@\$SSH_HOST" << EOF
        
        set -e # Habilitar manejo de errores
        echo "Starting deployment on production server..."

        # Navegar al directorio del proyecto
        cd /var/www/MoCA/

        # Actualizar el código
        echo "Pulling latest changes..."
        git pull origin main || { echo "Git pull failed"; exit 1; }

        # Limpiar caché
        echo "Clearing application cache..."
        php artisan cache:clear || { echo "Failed to clear cache"; exit 1; }

        # Instalar dependencias de Node.js
        echo "Building front-end assets..."
        npm run build || { echo "Build failed"; exit 1; }

        # Reiniciar la aplicación
        echo "Restarting application..."
        sudo systemctl restart apache2 || { echo "Failed to restart application"; exit 1; }

        echo "Deployment completed successfully!"
        EOF