name: Deploy to Server with VPN and SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install FortiClient VPN
      run: |
        # Importar la clave GPG
        wget -O - https://repo.fortinet.com/repo/forticlient/7.4/ubuntu22/DEB-GPG-KEY | gpg --dearmor | sudo tee /usr/share/keyrings/repo.fortinet.com.gpg

        # Añadir el repositorio de Fortinet
        echo "deb [arch=amd64 signed-by=/usr/share/keyrings/repo.fortinet.com.gpg] https://repo.fortinet.com/repo/forticlient/7.4/ubuntu22/ stable non-free" | sudo tee /etc/apt/sources.list.d/repo.fortinet.com.list

        # Actualizar listas de paquetes e instalar FortiClient
        sudo apt-get update
        sudo apt install -y forticlient || { echo "Failed to install FortiClient"; exit 1; }

    # 3️⃣ Conectar a la VPN
    - name: Connect to VPN
      env:
        VPN_USERNAME: ${{ secrets.VPN_USERNAME }}
        VPN_PASSWORD: ${{ secrets.VPN_PASSWORD }}
      run: |
        # Conectarse a la VPN
        echo $VPN_PASSWORD | forticlient connect --username $VPN_USERNAME --password-stdin || { echo "Failed to connect to VPN"; exit 1; }

    # 4️⃣ Configurar la clave SSH
    - name: Setup SSH Key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    # 5️⃣ Conectar al servidor y desplegar
    - name: Deploy to Server
      env:
        SSH_USER: ${{ secrets.SSH_USER }}
        SERVER_IP: ${{ secrets.SERVER_IP }}
      run: |
        ssh -o StrictHostKeyChecking=no $SSH_USER@$SERVER_IP << EOF
        set -e

        # Navegar al directorio del proyecto
        cd /var/www/MoCA

        # Obtener los últimos cambios del repositorio
        git pull origin main

        # Limpiar la caché
        php artisan cache:clear

        # Reiniciar el servicio
        sudo systemctl restart apache2

        echo "Deployment complete!"
        EOF